# This is a basic workflow to help you get started with Actions

name: PYTHON CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version:3.8
      - name: Install dependencies
        run: |
          python - m unittest
      - name: Lint with Flake8
        run: |
          pip instal flake8
          # Pare o workflow se encontrar problemas de estilo
          flake8. --count --select=E9,F63,F7,F82 --show-source --statistics
          #Exite com zero se nenhum erro for encontrado
          flake8. --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
     
